export { default as useStudents } from "./useStudents";
export { default as useEmployees } from "./useEmployees";
export { default as useCollege } from "./useCollege";
export { default as useDepartments } from "./useDepartments";
export { default as useSchoolYear } from "./useSchoolYear";
export { default as useSemesters } from "./useSemesters";
export { default as useThesis } from "./useThesis";
export { default as useThesisDetails } from "./useThesisDetails";
export { default as useFaculties } from "./useFaculties";
export { default as useThesisFaculty } from "./useThesisFaculty"; 
export { default as useFacultyList } from "./useFacultyList"; 
export { default as useStudentList } from "./useStudentList"; 
export { default as useGroup } from "./useGroup";
export { default as useGroupList } from "./useGroupList";
export { default as useEmailsGroup } from "./useEmailsGroup";
export { default as useGroupFaculty } from "./useGroupFaculty";
export { default as useThesisStudent } from "./useThesisStudent";
export { default as useThesisGroup } from "./useThesisGroup";
export { default as useThesisStages } from "./useThesisStages";
export { default as useDepartmentList } from "./useDepartmentList";
export { default as useCollegeList } from "./useCollegeList";
export { default as useDocDetails } from "./useDocDetails";
export { useFacultyDashboard,useFacultyDashboardRating,useRatingThesisSched } from "./useFacultyDashboard";
export {  useSchedule, useScheduleReport,useScheduleReports } from "./useSchedule";
export { default as useInlineComments } from "./useInlineComments";
export { default as useScreenRecord } from "./useScreenRecord";
export { default as useDashboard } from "./useDashboard";
export { default as useNotifications } from "./useNotifications";
export { default as useProfile } from "./useProfile";

